Added backup

diff --git a/releases/codefresh.yaml b/releases/codefresh.yaml
--- a/releases/codefresh.yaml
+++ b/releases/codefresh.yaml
@@ -152,7 +152,6 @@ releases:
 {{- else }}
       enabled: true
 {{- end }}
-    
 
     mongodb:
       ## Provision new volume claim
@@ -239,12 +238,6 @@ releases:
       varLibDockerVolume:
         storageSize: '{{ env "CODEFRESH_RUNNER_STORAGE_SIZE" | default "100Gi" }}'
 
-    backups:
-      #enabled: true
-      awsAccessKey: '{{ env "CODEFRESH_BACKUPS_AWS_ACCESS_KEY" }}'
-      awsSecretAccessKey: '{{ env "CODEFRESH_BACKUPS_AWS_ACCESS_SECRET" }}'
-      s3Url: s3://{{ env "CODEFRESH_BACKUPS_BUCKET_NAME" }}
-
     dockerconfigjson:
       auths:
         gcr.io:
@@ -285,6 +278,129 @@ releases:
         auths:
           gcr.io:
             auth: {{ cat "_json_key:" ( env "CODEFRESH_SA") | b64enc }}            
+
+- name: "cf-backup"
+  namespace: "codefresh"
+  labels:
+    chart: "raw"
+    component: "codefresh"
+    namespace: "codefresh"
+    vendor: "kubernetes-incubator"
+    default: "false"
+  chart: "incubator/raw"
+  version: "0.1.0"
+  wait: true
+  installed: {{ env "CODEFRESH_BACKUP_ENABLED" | default "true" }}
+  values:
+    - apiVersion: batch/v1beta1
+      kind: CronJob
+      metadata:
+        name: codefresh-backup
+      spec:
+        schedule: "0 1 * * *"
+        jobTemplate:
+          spec:
+            template:
+              spec:
+                initContainers:
+                  - name: mongo-backup
+                    image: mongo
+                    env:
+{{- if eq (env "CODEFRESH_USE_EXTERNAL_MONGODB" | default "false") "true" }}
+                    - name: MONGO_PWD
+                      value: {{ env "CODEFRESH_BACKUPS_MONGODB_ROOT_PASSWORD" }}
+                    - name: MONGO_ROOT_USER
+                      value: {{ env "CODEFRESH_BACKUPS_MONGODB_ROOT_USER" }}
+                    - name: MONGO_HOST
+                      value: {{ env "CODEFRESH_BACKUPS_MONGODB_HOST" }}
+                    - name: MONGO_PORT
+                      value: {{ env "CODEFRESH_BACKUPS_MONGODB_PORT" }}
+{- else }}
+                    - name: MONGO_PWD
+                      valueFrom:
+                        secretKeyRef:
+                          key: mongodb-root-password
+                          name: cf-mongodb
+                    - name: MONGO_ROOT_USER
+                      value: root
+                    - name: MONGO_HOST
+                      value: cf-mongodb
+                    - name: MONGO_PORT
+                      value: 27017
+{{- end }}
+                    command:
+                      - "/bin/sh"
+                      - "-ec"
+                      - |
+                        DATE=$(date +%Y%m%d_%H%M%S)
+                        echo $DATE > /backup/export_date
+                        mkdir -p /backup/$DATE/mongo
+                        echo "Starting Mongo backup"
+                        mongodump --out /backup/$DATE/mongo/ --host $MONGO_HOST:$MONGO_PORT -u $MONGO_ROOT_USER -p $MONGO_PWD || (echo "Mongo backup has failed for date $DATE"; exit 1)
+                        echo "Mongo backup completed successfully"
+                    volumeMounts:
+                      - name: backup-data
+                        mountPath: /backup
+                  - name: consul-backup
+                    image: consul
+                    command:
+                      - "/bin/sh"
+                      - "-ec"
+                      - |
+                        DATE=$(cat /backup/export_date)
+                        mkdir -p /backup/$DATE/consul
+                        echo "Starting Consul backup"
+                        curl http://cf-consul:8500/v1/snapshot > /backup/$DATE/consul/consul.bkp || (echo "Consul backup has failed for date $DATE"; exit 1)
+                        echo "Consul backup completed successfully"
+                    volumeMounts:
+                      - name: backup-data
+                        mountPath: /backup
+                  - name: redis-backup
+                    image: codefresh/rdbtools:master
+                    env:
+                      - name: REDIS_PWD
+                        value: ...
+                    command:
+                      - "/bin/sh"
+                      - "-ec"
+                      - |
+                        DATE=$(cat /backup/export_date)
+                        mkdir -p /backup/$DATE/redis
+                        echo "Starting Redis backup"
+                        redis-cli -u redis://cf-store:6379 -a $REDIS_PWD --rdb /backup/$DATE/redis/redis.bkp || (echo "Redis backup has failed for date $DATE"; exit 1)
+                        echo "Redis backup completed successfully"
+                    volumeMounts:
+                      - name: backup-data
+                        mountPath: /backup
+                containers:
+                  - name: aws-cli
+                    image: mesosphere/aws-cli
+                    env:
+                      - name: AWS_ACCESS_KEY_ID
+                        value: {{ env "CODEFRESH_BACKUPS_AWS_ACCESS_KEY" }}
+                      - name: AWS_SECRET_ACCESS_KEY
+                        value: {{ env "CODEFRESH_BACKUPS_AWS_ACCESS_SECRET" }}
+                      - name: S3_URL
+                        value: s3://{{ env "CODEFRESH_BACKUPS_BUCKET_NAME" }}
+                      - name: AWS_DEFAULT_REGION
+                        value: {{ env "CODEFRESH_BACKUPS_BUCKET_NAME" | default "us-west-2" }}
+                    command:
+                      - "/bin/sh"
+                      - "-ec"
+                      - |
+                        DATE=$(cat /backup/export_date)
+                        tar -zcvf cf-backup-$DATE.tar.gz /backup/$DATE/
+                        echo "Uploading to S3"
+                        aws s3 cp cf-backup-$DATE.tar.gz $S3_URL/cf-backup-$DATE.tar.gz
+                        rm cf-backup-$DATE.tar.gz
+                        rm -r /backup/$DATE
+                    volumeMounts:
+                      - name: backup-data
+                        mountPath: /backup
+                restartPolicy: Never
+                volumes:
+                  - name: backup-data
+                    emptyDir: {}
 
 - name: "cf-ext"
   namespace: "codefresh"
